SchoolSite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import include
import accounts.views as account_view


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', account_view.home_view, name='home'),
    url(r'', include('main_site_app.urls')),
    path('account/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admissions/', include('admission_app.urls')),
    # path('admissions/', account_view.admissions_view, name='admissions'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views



app_name = 'accounts'

urlpatterns = [
    path('register/', CustomerRegister.as_view(), name='register'),
    # path('login/', login_request, name='login'),
    path('login/', login_request, name='login'),
    path('logout/', logout_view, name='logout'),
    # path('change-password/', auth_views.PasswordChangeView.as_view()),
    # path('password_reset/', auth_views.PasswordResetView.as_view()),
    # path('password_reset_confirm/', auth_views.PasswordResetConfirmView.as_view()),
    # path('password_reset_done/', auth_views.PasswordChangeDoneView.as_view()),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view()),

]

main_site_app/urls.py
from django.urls import path
from .views import *

app_name = 'main_site_app'

urlpatterns = [
    path('', home_view, name='home'),
    path('attendance/', attendance_view, name='attendance'),
    path('parents-participantion/', parents_participation_view, name='parents-participantion'),
    path('general-rules/', general_rules_view, name='general-rules'),
    path('holiday-list/', holiday_list_view, name='holiday-list'),
    path('about/', about_view, name='about'),
    path('events/', events_view, name='events'),
    path('contact/', contact_view, name='contact'),
    path('school-admin/', student_list, name='student_list'),
    path('gallery/', gallery_view, name='gallery'),
    path('sportday/', sports_view, name='sportday'),
    path('wari/', wari_view, name='wari'),
    path('yoga/', yoga_view, name='yoga'),
    path('navratri/', navratri_view, name='navratri'),
    path('dushera/', dushera_view, name='dushera'),
    path('holi/', holi_view, name='holi'),
    path('funfair/', funfair_view, name='funfair'),
    path('ganpati/', ganpati_view, name='ganpati'),
    path('gathering/', gathering_view, name='gathering'),
    path('chrismas/', chrismas_view, name='chrismas'),
    path('donation/', donation_view, name='donation'),
    path('janmastami/', janmastami_view, name='janmastami'),
    path('other/', other_view, name='other'),

]

templates/base/asidebar.html
{% load static %}
<aside class="aside-menu">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab"><i class="icon-list"></i></a>
        </li>
<!--        <li class="nav-item">-->
<!--            <a class="nav-link" data-toggle="tab" href="#settings" role="tab"><i class="icon-settings"></i></a>-->
<!--        </li>-->
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="timeline" role="tabpanel">
            <div class="callout m-0 py-2 text-muted text-center bg-light text-uppercase">
                <small><b>Today</b></small>
            </div>
            <hr class="transparent mx-3 my-0">
            <div class="callout callout-warning m-0 py-3">
                <div class="avatar float-right">
                    <img src="{% static 'src/img/avatars/7.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
                </div>
                <div>Meeting with
                    <strong>Lucas</strong>
                </div>
                <small class="text-muted mr-3"><i class="icon-calendar"></i>&nbsp; 1 - 3pm</small>
                <small class="text-muted"><i class="icon-location-pin"></i>&nbsp; Palo Alto, CA</small>
            </div>
            <hr class="mx-3 my-0">
            <div class="callout callout-info m-0 py-3">
                <div class="avatar float-right">
                    <img src="{% static 'src/img/avatars/4.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
                </div>
                <div>Skype with
                    <strong>Megan</strong>
                </div>
                <small class="text-muted mr-3"><i class="icon-calendar"></i>&nbsp; 4 - 5pm</small>
                <small class="text-muted"><i class="icon-social-skype"></i>&nbsp; On-line</small>
            </div>
        </div>
        <div class="tab-pane p-3" id="settings" role="tabpanel">
            <h6>Settings</h6>
            <hr>
            <h6>System Utilization</h6>

            <div class="text-uppercase mb-1 mt-4">
                <small><b>CPU Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">348 Processes. 1/4 Cores.</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>Memory Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">11444GB/16384MB</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>SSD 1 Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">243GB/256GB</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>SSD 2 Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-success" role="progressbar" style="width: 10%" aria-valuenow="10"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">25GB/256GB</small>
        </div>
    </div>
</aside>

templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<!--Headers-->
{% include 'base/header.html' %}

<!-- BODY options, add following classes to body to change options

// Header options
1. '.header-fixed'					- Fixed Header

// Brand options
1. '.brand-minimized'       - Minimized brand (Only symbol)

// Sidebar options
1. '.sidebar-fixed'					- Fixed Sidebar
2. '.sidebar-hidden'				- Hidden Sidebar
3. '.sidebar-off-canvas'		- Off Canvas Sidebar
4. '.sidebar-minimized'			- Minimized Sidebar (Only icons)
5. '.sidebar-compact'			  - Compact Sidebar

// Aside options
1. '.aside-menu-fixed'			- Fixed Aside Menu
2. '.aside-menu-hidden'			- Hidden Aside Menu
3. '.aside-menu-off-canvas'	- Off Canvas Aside Menu

// Breadcrumb options
1. '.breadcrumb-fixed'			- Fixed Breadcrumb

// Footer options
1. '.footer-fixed'					- Fixed footer

-->

<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
<!--Navbar-->
{% include 'base/navbar.html' %}

<div class="app-body">
    <!--Sidebar-->
    {% include 'base/sidebar.html' %}

    <!-- Main content -->
    <main class="main">

        <!-- Breadcrumb -->
        {% include 'base/breadcrumb.html' %}

        <!-- Page contents -->
        <div class="container-fluid">
            <div class="animated fadeIn">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        <!-- /.conainer-fluid -->
    </main>


    <!--Aside bar-->
    {% include 'base/asidebar.html' %}

</div>

<!--Footer-->
{% include 'base/footer.html' %}

<!--JS-->
{% include 'base/js.html' %}

</body>
</html>

templates/base/breadcrumb.html
{% load static %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="#">Admin</a></li>
    <li class="breadcrumb-item active">Dashboard</li>

    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
        <div class="btn-group" role="group" aria-label="Button group">
            <a class="btn" href="#"><i class="icon-speech"></i></a>
            <a class="btn" href="{% url 'main_site_app:home' %}"><i class="icon-graph"></i> &nbsp;Dashboard</a>
            <a class="btn" href="#"><i class="icon-settings"></i> &nbsp;Settings</a>
        </div>
    </li>

    {% block breadcrumb %}
    {% endblock %}
</ol>

templates/base/footer.html
<footer class="app-footer">
    <span><a href="#">Province IT LLP</a> © 2021</span>
    <span class="ml-auto">Powered by <a href="#">Province IT LLP</a></span>
    {% block extrafooter %}
    {% endblock %}
</footer>

templates/base/header.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Circle Fintech">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <title>Province IT LLP</title>

    <!-- Icons -->
    <link href="{% static 'dist/vendors/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'dist/vendors/css/simple-line-icons.min.css' %}" rel="stylesheet">

    <!-- Main styles for this application -->
    <link href="{% static 'dist/css/style.css' %}" rel="stylesheet">

    {% block extrahead %}
    {% endblock %}
</head>

templates/base/js.html
{% load static %}

<!-- Bootstrap and necessary plugins -->
<script src="{% static 'dist/vendors/js/jquery.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/popper.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/pace.min.js' %}"></script>

<!-- Plugins and scripts required by all views -->
<!--Chart JS is commented out due to console errors-->
<!--<script src="{% static 'dist/vendors/js/Chart.min.js' %}"></script>-->

<!-- CoreUI main scripts -->

<script src="{% static 'dist/js/app.js' %}"></script>

<!-- Plugins and scripts required by this views -->

<!-- Custom scripts required by this view -->
<script src="{% static 'dist/js/views/main.js' %}"></script>
<script src="{% static 'custom.js' %}"></script>

{% block script %}

{% endblock %}

templates/base/navbar.html
{% load static %}
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav d-md-down-none">
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Settings</a>
        </li>
    </ul>

    <ul class="nav navbar-nav ml-auto">

        <li class="nav-item px-3">
            <p class="nav-link" style="padding-top: 10px">{{ request.user.username }}</p>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                <img src="{% static 'src/img/avatars/6.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span
                        class="badge badge-info">42</span></a>
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>
                <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
                <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
                <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-secondary">42</span></a>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-lock"></i> Logout</a>
            </div>
        </li>
    </ul>
    <button class="navbar-toggler aside-menu-toggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    {% block navbar %}
    {% endblock %}

</header>

templates/base/sidebar.html
{% load static %}
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main_site_app:home' %}"><i class="icon-speedometer"></i> TMV Site</a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-user"></i> Student</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main_site_app:student_list' %}">
                            <i class="nav-icon icon-puzzle"></i> Student List</a>
                    </li>
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="{% url 'attendance_count' %}">#}
                    {#                            <i class="nav-icon icon-puzzle"></i> Attendance</a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="{% url 'student_regi' %}">#}
                    {#                            <i class="nav-icon icon-puzzle"></i> Registration</a>#}
                    {#                    </li>#}
                </ul>
            </li>
            {#            <li class="nav-item nav-dropdown">#}
            {#                <a class="nav-link nav-dropdown-toggle" href="#">#}
            {#                    <i class="nav-icon icon-user"></i> Teachers</a>#}
            {#                <ul class="nav-dropdown-items">#}
            {#                    <li class="nav-item">#}
            {#                        <a class="nav-link" href="{% url 'teacher_list' %}">#}
            {#                            <i class="nav-icon icon-puzzle"></i> Teacher List</a>#}
            {#                    </li>#}
            {#                    <li class="nav-item">#}
            {#                        <a class="nav-link" href="{% url 'create_teacher' %}">#}
            {#                            <i class="nav-icon icon-puzzle"></i> Create New Teacher</a>#}
            {#                    </li>#}
            {#                </ul>#}
            {#            </li>#}
            {#            <li class="nav-item nav-dropdown">#}
            {#                <a class="nav-link nav-dropdown-toggle" href="#">#}
            {#                    <i class="nav-icon icon-user"></i> Employees</a>#}
            {#                <ul class="nav-dropdown-items">#}
            {#                    <li class="nav-item">#}
            {#                        <a class="nav-link" href="{% url 'employee_list' %}">#}
            {#                            <i class="nav-icon icon-puzzle"></i> Employee List</a>#}
            {#                    </li>#}
            {#                    <li class="nav-item">#}
            {#                        <a class="nav-link" href="{% url 'create_employee' %}">#}
            {#                            <i class="nav-icon icon-puzzle"></i> Create Employee</a>#}
            {#                    </li>#}
            {#                </ul>#}
            {#            </li>#}
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>

    {% block sidebar %}
    {% endblock %}
</div>