SchoolSite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import include
import accounts.views as account_view


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', account_view.home_view, name='home'),
    url(r'', include('main_site_app.urls')),
    path('account/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admissions/', include('admission_app.urls')),
    # path('admissions/', account_view.admissions_view, name='admissions'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views



app_name = 'accounts'

urlpatterns = [
    path('register/', CustomerRegister.as_view(), name='register'),
    # path('login/', login_request, name='login'),
    path('login/', login_request, name='login'),
    path('logout/', logout_view, name='logout'),
    # path('change-password/', auth_views.PasswordChangeView.as_view()),
    # path('password_reset/', auth_views.PasswordResetView.as_view()),
    # path('password_reset_confirm/', auth_views.PasswordResetConfirmView.as_view()),
    # path('password_reset_done/', auth_views.PasswordChangeDoneView.as_view()),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view()),

]

admission_app/urls.py
from django.urls import path
from .views import *

app_name = 'admission_app'

urlpatterns = [
    path('', primary_admissions_view, name='admissions'),
    path('application-list/', AdmissionApplicationView.as_view(), name='application-list'),
    path('primary-form/', primary_admissions_view, name='primary-form'),
    path('pri-primary/', pre_primary_admissions_view, name='pre-primary-form'),
    path('generate-pdf/<int:pk>/', GeneratePdf.as_view(), name='pdf-application-view'),
]

templates/students/attendance_count.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div class="card">
    <div class="card-header">
        <h1>Attendance Count</h1>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <form action="" method="GET">
                    Class: <input type="text" name="class_name" class="form-control">
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>

{% if student_list %}
    <table class="table table-responsive-sm table-bordered table-striped table-sm">
        <tr>
            <th>Name</th>
            <th>Admission ID</th>
            <th>Class</th>
            <th>Action</th>
        </tr>
        {% for std_list in student_list %}
            <tr>
                <td class="cls_name">{{ std_list.name }}</td>
                <td class="cls_admission">{{ std_list.admission_id }}</td>
                <td class="cls_class">{{ std_list.class_type.class_short_form }}</td>
                <td><button class="count_btn">Present</button></td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

{% endblock %}

templates/students/edit_student.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

{% include 'partials/_alerts.html' %}

<div class="card">
    <div class="card-header">
        <h2>Edit Student Info</h2>
    </div>
    <div class="card-body">
        <form action="" method="POST">
        {% csrf_token %}
        {{ edit_forms.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

{% endblock %}

templates/students/registration.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

{% include 'partials/_alerts.html' %}

<div class="card">
    <div class="card-header">
        <h2>Student Registration Form</h2>
    </div>
    <div class="card-body">
        <form action="" method="POST">
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/students/student_details.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="col-lg-7">
        <div class="card">
            <div class="card-header">
                 <i class="fa fa-align-justify"></i> Students Academic Info
            </div>
            <div class="card-body">
                <tbody>
                    <tr>
                        <td>Academic Year: {{ single_student.academic_year }}</td>
                        <br>
                        <td>Admission Date: {{ single_student.admission_date }}</td>
                        <br>
                        <td>Admission ID: {{ single_student.admission_id }}</td>
                        <br>
                        <td>Class: {{ single_student.class_type }}</td>
                        <br>
                        <td>Section: {{ single_student.section_type }}</td>
                        <br>
                        <td>Shift: {{ single_student.shift_type }}</td>
                    </tr>
                </tbody>
            </div>
        </div>
    </div>
    <div class="col-lg-5">
        <div class="card">
            <div class="card-header">
                 <i class="fa fa-align-justify"></i> Students Personal Info
            </div>
            <div class="card-body">

                <h6>{{ single_student.name }}</h6>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                 <i class="fa fa-align-justify"></i> Fathers Info
            </div>
            <div class="card-body">
                <tbody>
                    <tr>
                        <td>Fathers Name: {{ single_student.fathers_name }}</td>
                        <br>
                        <td>Fathers NID: {{ single_student.fathers_nid }}</td>
                        <br>
                        <td>Contact Number: {{ single_student.fathers_number }}</td>
                        <br>
                    </tr>
                </tbody>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                 <i class="fa fa-align-justify"></i> Mothers Info
            </div>
            <div class="card-body">
                <tbody>
                    <tr>
                        <td>Mothers Name: {{ single_student.mothers_name }}</td>
                        <br>
                        <td>Mothers NID: {{ single_student.mothers_nid }}</td>
                        <br>
                        <td>Contact Number: {{ single_student.mothers_number }}</td>
                        <br>
                    </tr>
                </tbody>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/students/student_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    {% include 'partials/_alerts.html' %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Students List
                    <span style="float: right"><label for="filterName"
                                                      style="margin-right: 10px">Search : </label> <input
                            id="filterName" type="text" placeholder="Keyword" class="search-key"></span>
                </div>
                <div class="card-body">
                    <table id="myTable" class="table table-responsive-sm table-bordered table-striped table-sm">
                        <thead>
                        <tr>
                            <th>SL</th>
                            <th>Admission Date</th>
                            <th>Name</th>
                            <th>Standard</th>
                            <th>Docs</th>
                            <th>Fees</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for student in students %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ student.created_date }}</td>
                                <td data-input="name">{{ student.student_surname }} {{ student.student_name }} {{ student.student_father_name }}</td>
                                <td>{{ student.admission_std }}</td>
                                <td>
                                    {% if not student.birth_certificate == '' %}
                                        <li><a href="/media/{{ student.birth_certificate }}">Birth Certificate</a></li>
                                    {% endif %}
                                    {% if not student.student_adhaar_card == '' %}
                                        <li><a href="/media/{{ student.student_adhaar_card }}">Adhaar Card</a></li>
                                    {% endif %}
                                    {% if not student.blood_group_certificate == '' %}
                                        <li><a href="/media/{{ student.blood_group_certificate }}">Blood Group</a></li>
                                    {% endif %}
                                    {% if not student.blood_group_certificate == '' %}
                                        <li><a href="/media/{{ student.fitness_certificate }}">Fitness Certificate</a>
                                        </li>
                                    {% endif %}
                                    {% if not student.transfer_certificate == '' %}
                                        <li><a href="/media/{{ student.fitness_certificate }}">Transfer Certificate</a>
                                        </li>
                                    {% endif %}
                                    {% if not student.report_card == '' %}
                                        <li><a href="/media/{{ student.report_card }}">Report Card</a>
                                        </li>
                                    {% endif %}
                                    {% if not student.caste_certificate == '' %}
                                        <li><a href="/media/{{ student.caste_certificate }}">Caste Certificate</a>
                                        </li>
                                    {% endif %}
                                    {% if not student.electricity_bill == '' %}
                                        <li><a href="/media/{{ student.electricity_bill }}">Electricity Bill</a>
                                        </li>
                                    {% endif %}
                                </td>
                                <td>
                                    Unpaid

                                </td>
                                <td>
                                    <a href="{% url 'admission_app:pdf-application-view' student.pk %}">Print/View</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            {% if students.has_other_pages %}
                <ul class="pagination">
                    {% if students.has_previous %}
                        <li class="page-item">
                            <a href="?page={{ students.previous_page_number }}" class="page-link">Prev</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">Prev</a>
                        </li>
                    {% endif %}
                    {% for i in students.paginator.page_range %}
                        {% if students.number == i %}
                            <li class="page-item active">
                                <a class="page-link">{{ i }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if students.has_next %}
                        <li class="page-item">
                            <a href="?page={{ students.next_page_number }}" class="page-link">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">Next</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>

    <script>
        function filterTable(event) {
            var filter = event.target.value.toUpperCase();
            var rows = document.querySelector("#myTable tbody").rows;

            for (var i = 0; i < rows.length; i++) {
                var firstCol = rows[i].cells[1].textContent.toUpperCase();
                var secondCol = rows[i].cells[2].textContent.toUpperCase();
                var thirdCol = rows[i].cells[3].textContent.toUpperCase();
                var fourthCol = rows[i].cells[5].textContent.toUpperCase();
                if (firstCol.indexOf(filter) > -1 || secondCol.indexOf(filter) > -1 || thirdCol.indexOf(filter) > -1 || fourthCol.indexOf(filter) > -1) {
                    rows[i].style.display = "";
                } else {
                    rows[i].style.display = "none";
                }
            }
        }

        document.querySelector('#filterName').addEventListener('keyup', filterTable, false);

    </script>

{% endblock %}